AdvancedOptions: false
RuntimeType: Container
DockerFilePath: docker/Dockerfile.base
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: ap-southeast-1
RepoName: oooYeoo/higress
RegionId: cn-hangzhou
CustomParameters: ''
Owner: oooYeoo
Branch: main
Platform: github
